version: "2"

services:
  dnsmasq:
    cap_add: 
      - ALL
    image: dnsmasq_server
    hostname: server
    container_name: dnsmasq
    privileged: true
    volumes:
      - /lib/modules/:/lib/modules/
      - /usr/src:/usr/src
      - ./conf/dnsmasq.conf:/etc/dnsmasq.conf
      - ./scripts/resolutions:/resolutions
      - ./scripts/entrypoint.sh:/entrypoint.sh
    command: ['./entrypoint.sh'] 
    entrypoint:
      - /bin/bash
    networks:
      default:
        ipv4_address: 172.30.0.5
    tty: true

  container1:
    cap_add: 
      - ALL
    image: ubuntu:18.04
    hostname: container1
    container_name: container1
    privileged: true
    depends_on:
      - dnsmasq
    volumes:
      - ./scripts/insertip.sh:/insertip.sh
    dns:
      - 172.30.0.5
    command: ['./insertip.sh']
    entrypoint:
      - /bin/bash
    networks:
        default:
          ipv4_address: 172.30.0.6
    tty: true

  container2:
    cap_add: 
      - ALL
    image: ubuntu:18.04
    hostname: container2
    container_name: container2
    privileged: true
    depends_on:
      - dnsmasq
    volumes:
      - ./scripts/insertip.sh:/insertip.sh
    command: ['./insertip.sh']
    dns:
      - 172.30.0.5
    entrypoint:
      - /bin/bash
    networks:
        default:
          ipv4_address: 172.30.0.7
    tty: true

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1